# Generated by Django 3.1.3 on 2021-01-16 11:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': "Раздел 'О Нас",
                'verbose_name_plural': "Разделы 'О Нас",
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=20, verbose_name='Название сайта')),
                ('telephone_num', models.CharField(max_length=20, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('org_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название организации')),
                ('top_img', models.ImageField(blank=True, null=True, upload_to='setting', verbose_name='Изображение в верхнем разделе')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='setting', verbose_name='favicon')),
                ('logo_top', models.ImageField(blank=True, null=True, upload_to='setting', verbose_name='Логотип в шапке')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fab fa-fw fa-whatsapp', 'whatsapp'), ('fab fa-fw fa-viber', 'viber'), ('fab fa-fw fa-telegram-plane', 'telegram'), ('fab fa-fw fa-instagram', 'instagram'), ('fab fa-fw fa-vk', 'vk'), ('fab fa-fw fa-facebook-f', 'facebook'), ('fab fa-fw fa-odnoklassniki', 'odnoklassniki'), ('fab fa-fw fa-twitter', 'twitter'), ('fab fa-fw fa-youtube', 'youtube')], max_length=512, verbose_name='Название соц. сети')),
                ('link', models.CharField(max_length=512, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='Токен бота')),
            ],
            options={
                'verbose_name': 'Настройки telegram бота',
                'verbose_name_plural': 'Настройки telegram бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramChenalID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=150, verbose_name='ID чата')),
                ('tele_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='settings.telegrambot')),
            ],
            options={
                'verbose_name': 'Чаты',
                'verbose_name_plural': 'Чат',
            },
        ),
        migrations.CreateModel(
            name='TelegramChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chenal_id', models.CharField(max_length=150, verbose_name='ID канала')),
                ('tele_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chenal', to='settings.telegrambot')),
            ],
            options={
                'verbose_name': 'Каналы',
                'verbose_name_plural': 'Канал',
            },
        ),
    ]
