# Generated by Django 3.1.3 on 2021-01-16 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_invite', to='feedback.feedback', verbose_name='Заявка обратной связи')),
            ],
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Очень хорошо!', 'Очень хорошо!'), ('Хорошо!', 'Хорошо!'), ('Удовлетворительно!', 'Удовлетворительно!'), ('Плохо!', 'Плохо!'), ('Очень плохо!', 'Очень плохо!')], max_length=20, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=200, verbose_name='Отзыв')),
                ('verified', models.BooleanField(default=False, verbose_name='Верификация')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall', to='feedback.feedback', verbose_name='Заявка обратной связи')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
