# Generated by Django 3.1.3 on 2021-01-16 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефонный номер')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('in_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('performed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Заявка (Обратная связь)',
                'verbose_name_plural': 'Заявки (Обратная связь)',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сomment', models.TextField(verbose_name='Комментарий')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='feedback.feedback', verbose_name='Заявка обратной связи')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
