# Generated by Django 3.1.3 on 2021-01-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='сomment',
            new_name='comment',
        ),
    ]
